"use client";

import React, { useState } from 'react';

const BRAND_COLOR = '#9A7D2E'; // GV Gold
const BG_COLOR = '#FAFAF8';
const TEXT_COLOR = '#1a1a1a';
const SECONDARY_TEXT = '#4b5563';

// Mock function to generate templates for preview (since we can't import the server-side one directly easily in client components without more setup)
const getBaseTemplate = (content: string) => `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: sans-serif; line-height: 1.6; color: ${TEXT_COLOR}; background-color: ${BG_COLOR}; margin: 0; padding: 20px; }
    .container { max-width: 600px; margin: 0 auto; background: white; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden; }
    .header { padding: 40px 20px; text-align: center; border-bottom: 2px solid ${BRAND_COLOR}; }
    .logo { font-size: 24px; font-weight: 700; color: ${TEXT_COLOR}; letter-spacing: 2px; margin: 0; }
    .content { padding: 40px; }
    .footer { padding: 30px; text-align: center; font-size: 12px; color: ${SECONDARY_TEXT}; background: #f9fafb; border-top: 1px solid #e5e7eb; }
    .button { display: inline-block; padding: 12px 24px; background-color: ${BRAND_COLOR}; color: white !important; text-decoration: none; border-radius: 4px; font-weight: 600; margin-top: 20px; }
    .highlight { color: ${BRAND_COLOR}; font-weight: 700; }
    .divider { height: 1px; background-color: #e5e7eb; margin: 30px 0; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header"><h1 class="logo">GV CAPITAL <span style="color: ${BRAND_COLOR};">TRUST</span></h1></div>
    <div class="content">${content}</div>
    <div class="footer"><p>&copy; 2026 GV Capital Trust. All rights reserved.</p></div>
  </div>
</body>
</html>
`;

const templates = {
  welcome: `
    <h2>Welcome Aboard</h2>
    <p>Dear John Doe,</p>
    <p>Thank you for choosing <span class="highlight">GV Capital Trust</span> for your financial journey. Your account has been successfully created.</p>
    <p>To start exploring our institutional-grade investment management services, please log in to your dashboard.</p>
    <div class="divider"></div>
    <p><strong>Next Step:</strong> Complete your KYC verification to unlock full account features.</p>
    <a href="#" class="button">Go to Dashboard</a>
  `,
  kyc_verified: `
    <h2>Verification Complete</h2>
    <p>Dear John Doe,</p>
    <p>We are pleased to inform you that your identity verification (KYC) has been <span class="highlight">successfully verified</span>.</p>
    <p>Your account is now fully active, and you can begin making deposits and managing your investments.</p>
    <a href="#" class="button">Make Your First Deposit</a>
  `,
  deposit: `
    <h2>Deposit under Review</h2>
    <p>Dear John Doe,</p>
    <p>We have received your deposit request of <span class="highlight">USD 5,000.00</span>.</p>
    <p>Our team is currently verifying the transaction. Funds will be reflected in your wallet once confirmed.</p>
    <div class="divider"></div>
    <p>Thank you for your continued trust in GV Capital.</p>
  `,
  withdrawal: `
    <h2>Withdrawal Processing</h2>
    <p>Dear John Doe,</p>
    <p>Your withdrawal request for <span class="highlight">USD 1,200.00</span> has been received.</p>
    <p>Your request is currently being processed by our finance team. You will be notified once the funds have been dispatched.</p>
    <div class="divider"></div>
    <p>Transaction ID: ABC-123-XYZ</p>
  `,
  dividend: `
    <h2>Your Assets are Working</h2>
    <p>Dear John Doe,</p>
    <p>We are pleased to announce that a dividend of <span class="highlight">USD 450.00</span> has been credited to your account.</p>
    <p>This payment represents your share of the profits generated by our institutional management strategies.</p>
    <div class="divider"></div>
    <a href="#" class="button">View Performance</a>
  `
};

export default function EmailPreviewPage() {
  const [selected, setSelected] = useState<keyof typeof templates>('welcome');

  return (
    <div className="min-h-screen bg-gray-50 p-8">
      <div className="max-w-6xl mx-auto">
        <header className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Institutional Email Previews</h1>
          <p className="text-gray-600">Review the professional templates for GV Capital Trust.</p>
        </header>

        <div className="flex gap-8">
          <div className="w-1/4">
            <nav className="flex flex-col gap-2">
              {Object.keys(templates).map((key) => (
                <button
                  key={key}
                  onClick={() => setSelected(key as any)}
                  className={`text-left px-4 py-3 rounded-lg font-medium transition-all ${
                    selected === key 
                      ? 'bg-[#9A7D2E] text-white shadow-lg' 
                      : 'bg-white text-gray-700 hover:bg-gray-100 shadow-sm'
                  }`}
                >
                  {key.replace('_', ' ').toUpperCase()}
                </button>
              ))}
            </nav>
          </div>

          <div className="w-3/4 bg-white rounded-xl shadow-2xl border border-gray-100 overflow-hidden">
             <iframe
                title="Email Preview"
                srcDoc={getBaseTemplate(templates[selected])}
                className="w-full h-[700px] border-none"
             />
          </div>
        </div>
      </div>
    </div>
  );
}
